import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { describe, it, expect } from "vitest";

/**
 * quality-rules.json bundling contract (issue #1). Written RED-first: the
 * engine ships the shared quality minimums as a package artifact so the
 * content repos can mirror them from the pinned engine release instead of
 * owning a repo-local copy. The file was originally generated by
 * adaptive-learner's scripts/generate_lesson_schema.py and copied verbatim by
 * the schema-sync procedure - the same channel as lesson.schema.json; since
 * the v0.6.0 authority flip its canonical home is this engine.
 */

const repoPath = (relativePath: string): string =>
  fileURLToPath(new URL(`../${relativePath}`, import.meta.url));

const readRepoJson = (relativePath: string): Record<string, unknown> =>
  JSON.parse(readFileSync(repoPath(relativePath), "utf8")) as Record<string, unknown>;

const QUALITY_RULE_KEYS = [
  "minExerciseTypes",
  "minExercisesPerLesson",
  "minFreeTextAccepts",
  "minMatchingPairs",
  "minTheorySteps",
];

describe("quality-rules.json package artifact", () => {
  it("exists as schema/quality-rules.json and parses as JSON", () => {
    expect(existsSync(repoPath("schema/quality-rules.json"))).toBe(true);
    expect(() => readRepoJson("schema/quality-rules.json")).not.toThrow();
  });

  it("carries exactly the shared quality minimum rules, each a positive integer", () => {
    const qualityRules = readRepoJson("schema/quality-rules.json");
    const rules = qualityRules.rules as Record<string, unknown>;
    expect(Object.keys(rules).sort()).toEqual(QUALITY_RULE_KEYS);
    for (const ruleKey of QUALITY_RULE_KEYS) {
      const ruleValue = rules[ruleKey];
      expect(Number.isInteger(ruleValue), `${ruleKey} must be an integer`).toBe(true);
      expect(ruleValue as number).toBeGreaterThan(0);
    }
  });

  it("ships in the npm package (files whitelist + exports subpath)", () => {
    const packageManifest = readRepoJson("package.json");
    const packagedFiles = packageManifest.files as string[];
    expect(packagedFiles).toContain("schema");
    const exportedSubpaths = packageManifest.exports as Record<string, unknown>;
    expect(exportedSubpaths["./schema/quality-rules.json"]).toBe("./schema/quality-rules.json");
    expect(existsSync(repoPath("schema/quality-rules.json"))).toBe(true);
  });

  it("tracks the bundled lesson schema version ($schema-version === x-schema-version)", () => {
    const qualityRules = readRepoJson("schema/quality-rules.json");
    const lessonSchema = readRepoJson("schema/lesson.schema.json");
    expect(qualityRules["$schema-version"]).toBe(lessonSchema["x-schema-version"]);
  });
});
